; ./rmac/rmac -s ~oall -lsyn6prn -ps -isrc src/syn6.s -o syn6

;
; +-------------------------------------------------------------------------+
; |      This file was generated by The Interactive Disassembler (IDA)      |
; |           Copyright (c) 2023 Hex-Rays, <support@hex-rays.com>           |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 1B3E9FED0DAD9F0F355294B10BBCD37C855E804F6DA45FF79CA691FAA364EA0C
; Input MD5    : FA469501378C26188E3E25AD7BD3935E
; Input CRC32  : 9939947D

; File Name   : Z:\home\robert\Dev\t2k-25easypieces\notebooks\syn6.bin
; Format      : Binary file
; Base Address: 0000h Range: 0000h - 2178h Loaded length: 2178h

; Processor       : 68000
; Target assembler: 680x0 Assembler in MRI compatible mode
; This file should be compiled with "as -M"

; ===========================================================================

; Segment type: Pure code
; segment "ROM"
.include "jaguar.inc"
.include "syn6.inc"

trap_7_instruction_entry:dc.b 'Copyright (1993) Imagitec Design, Inc '
                                        ; CODE XREF: ROM:0000052E↓p
                                        ; ROM:0000054A↓p ...
                                        ; initial_sp
                                        ; line_f_emulator_entry
; ---------------------------------------------------------------------------
                movem.l d0-d7/a0-a6,-(sp)
                move.l  #0,($F1A114).l
                move.l  #0,($F1A100).l
                movea.l #0,a1
                movea.l #0,a0
                move.l  a0,d0
                move.l  #0,d1
                sub.l   d0,d1
                lsr.l   #2,d1

loc_56:                                 ; CODE XREF: ROM:00000058↓j
                move.l  (a0)+,(a1)+
                dbf     d1,loc_56
                movea.l #$F1B800,a0
                jsr     (sub_B4).l
                jsr     (sub_B4).l
                jsr     (sub_B4).l
                jsr     (sub_B4).l
                jsr     (sub_B4).l
                jsr     (sub_B4).l
                move.l  #$1B,($F1A150).l
                move.l  #$15,($F1A154).l
                move.l  #0,($F1A110).l
                move.l  #1,($F1A114).l
                movem.l (sp)+,d0-d7/a0-a6
                rts

; =============== S U B R O U T I N E =======================================


sub_B4:                                 ; CODE XREF: ROM:00000062↑p
                                        ; ROM:00000068↑p ...
                move.l  #$FFFFFFFC,(a0)+ ; level_1_interrupt_autovector_entry
                                        ; level_4_interrupt_autovector_entry
                move.l  #$4000,(a0)+
                clr.l   d0
                move.l  d0,(a0)+
                move.l  d0,(a0)+
                move.l  d0,(a0)+
                move.l  d0,(a0)+
                move.l  d0,(a0)+
                move.l  d0,(a0)+
                rts
; End of function sub_B4

; ---------------------------------------------------------------------------
aImagitecDesign:dc.b 'Imagitec Design,Inc ',$BD,' 1993 written by Trev'
; ---------------------------------------------------------------------------
INIT_SOUND:
                movem.l d0-d7/a0-a6,-(sp)

loc_FE:                                 ; CODE XREF: ROM:loc_FE↑p
                bsr.w   loc_FE+2
                bsr.w   initpit2
                move.l  #$FFFFFFFF,(trap_7_instruction_entry).l ; "Copyright (1993) Imagitec Design, Inc "
                movem.l (sp)+,d0-d7/a0-a6
                rts
; ---------------------------------------------------------------------------
                movem.l d1-d7/a0-a6,-(sp)
                bsr.w   sub_684
                lea     (dword_1DE0).l,a6
                move.l  #2,dword_1DF0-dword_1DE0(a6)
                movem.l (sp)+,d1-d7/a0-a6
                rts
; ---------------------------------------------------------------------------
                move.l  #$1AC,d0
                lsl.l   #8,d0
                move.l  #$321,d1
                moveq   #$6C,d2 ; 'l'
                lea     (word_1792).l,a0

loc_148:                                ; CODE XREF: ROM:00000164↓j
                move.l  d0,d3
                divu.w  d2,d3
                andi.l  #$FFFF,d3
                mulu.w  #$1C,d3
                divu.w  #$2B,d3 ; '+'
                andi.l  #$FFFF,d3
                move.w  d3,(a0)+
                addq.l  #1,d2
                dbf     d1,loc_148
                rts

; =============== S U B R O U T I N E =======================================


initpit2:
                move.l  #$EF74,d0
                move.l  #$321,d1
                moveq   #$6C,d2 ; 'l'
                move.l  #$8000,d4
                lea     (word_1792).l,a0

loc_184:                                ; CODE XREF: initpit2+2E↓j
                move.l  d0,d3
                divu.w  d2,d3
                swap    d3
                add.l   d4,d3
                swap    d3
                andi.l  #$FFFF,d3
                move.w  d3,(a0)+
                addq.l  #1,d2
                dbf     d1,loc_184
                rts
; End of function initpit2

; ---------------------------------------------------------------------------
NT_VBL:
                movem.l d0-d2/d7-a4,-(sp)
                bsr.w   sub_824
                lea     byte_FFE(pc),a3
                pea     (a3)
                lea     $210(a3),a3
                lea     word_1792(pc),a1
                lea     word_FDE(pc),a0
                movea.l #$F1B800,a4
                moveq   #3,d7
                lea     dword_1DE0(pc),a2
                pea     (a2)

loc_1C6:                                ; CODE XREF: ROM:00000268↓j
                moveq   #0,d0
                move.w  $18(a3),d0
                beq.s   loc_1DC
                subi.w  #$6C,d0 ; 'l'
                lsl.w   #1,d0
                move.w  (a1,d0.w),d0
                move.l  d0,$C(a4)

loc_1DC:                                ; CODE XREF: ROM:000001CC↑j
                clr.l   d0
                move.w  $1A(a3),d0
                lsr.w   #1,d0
                move.w  d0,2(a2)
                move.l  (a2),4(a4)
                move.l  0(a0),d1
                blt.s   loc_25C
                move.l  #$FFFFFFFF,0(a0)
                move.w  #0,(a2)
                move.l  (a2),4(a4)
                move.l  #$FFFFFFFC,(a4)
                move.l  d1,$10(a4)
                tst.l   d1
                beq.s   loc_25C
                move.l  4(a0),d0
                lsr.l   #8,d0
                move.l  d0,8(a4)
                moveq   #0,d2
                move.w  $10(a3),d2
                lsl.l   #8,d2
                lsl.l   #1,d2
                move.l  d2,$14(a4)
                move.l  $C(a3),d0
                cmp.l   d1,d0
                bne.s   loc_238
                cmp.l   #$200,d2
                beq.s   loc_244

loc_238:                                ; CODE XREF: ROM:0000022E↑j
                move.l  d0,$1C(a4)
                move.w  #$8000,(a2)
                move.l  (a2),4(a4)

loc_244:                                ; CODE XREF: ROM:00000236↑j
                move.l  $C(a4),d0
                neg.l   d0
                move.l  d0,$18(a4)
                move.l  #0,$18(a4)
                move.l  #$1C,(a4)

loc_25C:                                ; CODE XREF: ROM:000001F0↑j
                                        ; ROM:0000020E↑j
                lea     $20(a4),a4
                addq.l  #8,a0
                lea     $34(a3),a3
                addq.l  #4,a2
                dbf     d7,loc_1C6
                movea.l (sp)+,a2
                movea.l (sp)+,a3
                tst.w   $14(a2)
                beq.s   loc_2AA
                moveq   #0,d1
                move.w  $20E(a3),d1
                move.l  $1E(a2),d0
                add.l   $10(a2),d1
                cmp.l   d0,d1
                ble.s   loc_292
                move.l  d0,d1
                move.w  #0,$14(a2)
                bra.s   loc_2A6
; ---------------------------------------------------------------------------

loc_292:                                ; CODE XREF: ROM:00000286↑j
                cmp.l   #0,d1
                bge.s   loc_2A6
                move.l  #0,d1
                move.w  #0,$14(a2)

loc_2A6:                                ; CODE XREF: ROM:00000290↑j
                                        ; ROM:00000298↑j
                move.w  d1,$20E(a3)

loc_2AA:                                ; CODE XREF: ROM:00000274↑j
                movem.l (sp)+,d0-d2/d7-a4
                rts
; ---------------------------------------------------------------------------
                movem.l d1-d7/a2-a6,-(sp)
                tst.w   d1
                bne.s   loc_2BC
                move.w  0(a0),d1

loc_2BC:                                ; CODE XREF: ROM:000002B6↑j
                movea.l #0,a3
                lea     dword_1DE0(pc),a2
                tst.b   byte_1E06-dword_1DE0(a2)
                beq.w   loc_398
                tst.b   $27(a2)
                beq.s   loc_2E2
                moveq   #1,d6
                movea.l #$F1B880,a4
                lea     $30(a2),a2
                bra.s   loc_2EE
; ---------------------------------------------------------------------------

loc_2E2:                                ; CODE XREF: ROM:000002D2↑j
                moveq   #5,d6
                movea.l #$F1B800,a4
                lea     $28(a2),a2

loc_2EE:                                ; CODE XREF: ROM:000002E0↑j
                pea     (a4)
                pea     (a2)
                move.w  d6,d7

loc_2F4:                                ; CODE XREF: ROM:00000306↓j
                cmpi.l  #$FFFFFFFC,(a4)
                bne.s   loc_300
                move.w  #$FFFF,(a2)

loc_300:                                ; CODE XREF: ROM:000002FA↑j
                lea     $20(a4),a4
                addq.l  #2,a2
                dbf     d7,loc_2F4
                lea     dword_1DE0(pc),a6
                movea.l (sp)+,a5
                movea.l (sp)+,a2
                movea.l #0,a3
                movea.l a3,a4
                move.w  d1,d5
                move.w  d6,d7

loc_31E:                                ; CODE XREF: ROM:0000032E↓j
                cmp.w   (a5),d5
                blt.s   loc_328
                movea.l a2,a4
                movea.l a5,a3
                move.w  (a5),d5

loc_328:                                ; CODE XREF: ROM:00000320↑j
                addq.l  #2,a5
                lea     $20(a2),a2
                dbf     d7,loc_31E
                cmpa.l  #0,a4
                beq.s   loc_398
                move.w  d1,(a3)
                move.l  #$FFFFFFFC,(a4)
                move.l  4(a0),$10(a4)
                move.l  8(a0),8(a4)
                move.l  $C(a0),$1C(a4)
                move.l  #0,$18(a4)
                tst.w   d2
                bne.s   loc_364
                move.l  $1A(a6),d2

loc_364:                                ; CODE XREF: ROM:0000035E↑j
                ext.l   d2
                lsl.l   #6,d2
                move.l  $10(a0),$14(a4)
                beq.s   loc_374
                bset    #$1F,d2

loc_374:                                ; CODE XREF: ROM:0000036E↑j
                move.l  d2,4(a4)
                tst.l   d3
                bne.s   loc_380
                move.w  2(a0),d3

loc_380:                                ; CODE XREF: ROM:0000037A↑j
                mulu.w  #$1C,d3
                divu.w  #$2B,d3 ; '+'
                andi.l  #$FFFF,d3
                move.l  d3,$C(a4)
                move.l  #$1C,(a4)

loc_398:                                ; CODE XREF: ROM:000002CA↑j
                                        ; ROM:00000338↑j
                move.l  a3,d0
                beq.s   loc_3AA
                lea     dword_1DE0(pc),a2
                lea     dword_1E08-dword_1DE0(a2),a2
                sub.l   a2,d0
                lsr.w   #1,d0
                addq.w  #1,d0

loc_3AA:                                ; CODE XREF: ROM:0000039A↑j
                movem.l (sp)+,d1-d7/a2-a6
                rts
; ---------------------------------------------------------------------------
                movem.l d4-d7/a0-a6,-(sp)
                subq.w  #1,d1
                lsl.w   #5,d1
                movea.l #$F1B800,a0
                btst    #0,d0
                beq.s   loc_3CE
                move.l  #$FFFFFFFC,(a0,d1.w)
                bra.s   loc_424
; ---------------------------------------------------------------------------

loc_3CE:                                ; CODE XREF: ROM:000003C2↑j
                btst    #1,d0
                beq.s   loc_3E0
                move.l  4(a0,d1.w),d4
                bclr    #$1F,d4
                move.l  d4,4(a0,d1.w)

loc_3E0:                                ; CODE XREF: ROM:000003D2↑j
                btst    #2,d0
                beq.s   loc_402
                move.l  4(a0,d1.w),d4
                asl.w   #7,d2
                add.w   d2,d4
                bvc.s   loc_3F6
                move.w  #$7FFF,d4
                bra.s   loc_3FC
; ---------------------------------------------------------------------------

loc_3F6:                                ; CODE XREF: ROM:000003EE↑j
                bpl.s   loc_3FC
                move.w  #0,d4

loc_3FC:                                ; CODE XREF: ROM:000003F4↑j
                                        ; ROM:loc_3F6↑j
                move.w  d4,d2
                move.l  d4,4(a0,d1.w)

loc_402:                                ; CODE XREF: ROM:000003E4↑j
                btst    #3,d0
                beq.s   loc_424
                move.l  $C(a0,d1.w),d4
                ext.l   d3
                add.l   d3,d4
                bvc.s   loc_41A
                move.l  #$7FFFFFFF,d4
                bra.s   loc_41E
; ---------------------------------------------------------------------------

loc_41A:                                ; CODE XREF: ROM:00000410↑j
                bpl.s   loc_41E
                moveq   #0,d4

loc_41E:                                ; CODE XREF: ROM:00000418↑j
                                        ; ROM:loc_41A↑j
                move.l  d4,d3
                move.l  d4,$C(a0,d1.w)

loc_424:                                ; CODE XREF: ROM:000003CC↑j
                                        ; ROM:00000406↑j
                movem.l (sp)+,d4-d7/a0-a6
                rts
; ---------------------------------------------------------------------------
                movem.l d1-d2/a0-a1,-(sp)
                lea     dword_1DE0(pc),a0
                tst.w   d1
                beq.s   loc_43C
                lea     $1A(a0),a1
                bra.s   loc_440
; ---------------------------------------------------------------------------

loc_43C:                                ; CODE XREF: ROM:00000434↑j
                lea     $1E(a0),a1

loc_440:                                ; CODE XREF: ROM:0000043A↑j
                move.l  (a1),d2
                ext.l   d0
                tst.l   d0
                bpl.s   loc_45A
                add.l   d0,d2
                cmp.l   #0,d2
                bge.s   loc_46A
                move.l  #0,d2
                bra.s   loc_46A
; ---------------------------------------------------------------------------

loc_45A:                                ; CODE XREF: ROM:00000446↑j
                add.l   d0,d2
                cmp.l   #$FF,d2
                ble.s   loc_46A
                move.l  #$FF,d2

loc_46A:                                ; CODE XREF: ROM:00000450↑j
                                        ; ROM:00000458↑j ...
                move.w  #1,$14(a0)
                move.l  d2,(a1)
                tst.w   d1
                bne.s   loc_47E
                lea     byte_FFE(pc),a0
                move.w  d2,word_120C-byte_FFE(a0)

loc_47E:                                ; CODE XREF: ROM:00000474↑j
                move.l  d2,d0
                movem.l (sp)+,d1-d2/a0-a1
                rts
; ---------------------------------------------------------------------------
                movem.l d1-d2/a0-a1,-(sp)
                lea     dword_1DE0(pc),a0
                tst.w   d1
                beq.s   loc_498
                lea     $1A(a0),a1
                bra.s   loc_49C
; ---------------------------------------------------------------------------

loc_498:                                ; CODE XREF: ROM:00000490↑j
                lea     $1E(a0),a1

loc_49C:                                ; CODE XREF: ROM:00000496↑j
                move.l  d0,d2
                cmp.l   #0,d2
                bge.s   loc_4AE
                move.l  #0,d2
                bra.s   loc_4BC
; ---------------------------------------------------------------------------

loc_4AE:                                ; CODE XREF: ROM:000004A4↑j
                cmp.l   #$FF,d2
                ble.s   loc_4BC
                move.l  #$FF,d2

loc_4BC:                                ; CODE XREF: ROM:000004AC↑j
                                        ; ROM:000004B4↑j
                move.w  #1,$14(a0)
                move.l  d2,(a1)
                tst.w   d1
                bne.s   loc_4D0
                lea     byte_FFE(pc),a0
                move.w  d2,word_120C-byte_FFE(a0)

loc_4D0:                                ; CODE XREF: ROM:000004C6↑j
                move.l  d2,d0
                movem.l (sp)+,d1-d2/a0-a1
                rts
; ---------------------------------------------------------------------------
FADEUP:
                movem.l d0/a0,-(sp)
                lea     dword_1DE0(pc),a0
                move.l  dword_1DFE-dword_1DE0(a0),d0
                lea     byte_FFE(pc),a0
                move.w  d0,word_120C-byte_FFE(a0)
                movem.l (sp)+,d0/a0
                rts
; ---------------------------------------------------------------------------
FADEDOWN:
                move.l  a0,-(sp)
                lea     dword_1DE0(pc),a0
                move.l  #2,dword_1DF0-dword_1DE0(a0)
                move.w  #1,$14(a0)
                movea.l (sp)+,a0
                rts
; ---------------------------------------------------------------------------
                move.l  a0,-(sp)
                lea     dword_1DE0(pc),a0
                move.l  #$FFFFFFFE,dword_1DF0-dword_1DE0(a0)
                move.w  #1,$14(a0)
                movea.l (sp)+,a0
                rts
; ---------------------------------------------------------------------------
                move.l  a4,-(sp)
                move.l  #0,(trap_7_instruction_entry).l ; "Copyright (1993) Imagitec Design, Inc "
                jsr     (trap_7_instruction_entry).l ; "Copyright (1993) Imagitec Design, Inc "
                lea     dword_1DE0(pc),a4
                st      byte_1E07-dword_1DE0(a4)
                move.w  #1,$14(a4)
                movea.l (sp)+,a4
                rts
; ---------------------------------------------------------------------------
                movem.l d7/a3-a4,-(sp)
                jsr     (trap_7_instruction_entry).l ; "Copyright (1993) Imagitec Design, Inc "
                lea     dword_1DE0(pc),a4
                sf      byte_1E07-dword_1DE0(a4)
                lea     $28(a4),a3
                movea.l #$F1B800,a4
                moveq   #3,d7

loc_564:                                ; CODE XREF: ROM:0000057A↓j
                move.l  #$FFFFFFFC,(a4)
                move.l  #0,4(a4)
                move.w  #$FFFF,(a3)+
                lea     $20(a4),a4
                dbf     d7,loc_564
                move.l  #$FFFFFFFF,(trap_7_instruction_entry).l ; "Copyright (1993) Imagitec Design, Inc "
                movem.l (sp)+,d7/a3-a4
                rts
; ---------------------------------------------------------------------------
ENABLE_F:
                movem.l a6,-(sp)
                lea     dword_1DE0(pc),a6
                st      byte_1E06-dword_1DE0(a6)
                movem.l (sp)+,a6
                rts
; ---------------------------------------------------------------------------
                movem.l d7/a6,-(sp)
                lea     dword_1DE0(pc),a6
                sf      byte_1E06-dword_1DE0(a6)
                tst.b   $27(a6)
                beq.s   loc_5B6
                moveq   #5,d7
                bra.s   loc_5B8
; ---------------------------------------------------------------------------

loc_5B6:                                ; CODE XREF: ROM:000005B0↑j
                moveq   #1,d7

loc_5B8:                                ; CODE XREF: ROM:000005B4↑j
                movea.l #$F1B800,a6
                lea     $A0(a6),a6

loc_5C2:                                ; CODE XREF: ROM:000005D4↓j
                move.l  #$FFFFFFFC,(a6)
                move.l  #0,4(a6)
                lea     -$20(a6),a6
                dbf     d7,loc_5C2
                movem.l (sp)+,d7/a6
                rts
; ---------------------------------------------------------------------------
                movem.l d1/a0-a2,-(sp)
                lea     dword_1DDC(pc),a1
                lea     (a1,d0.w),a1
                move.b  (a1),d1
                lea     byte_FFE(pc),a0
                lea     word_120E-byte_FFE(a0),a0
                mulu.w  #$34,d0 ; '4'
                lea     $32(a0,d0.w),a2
                move.b  (a2),d0
                move.b  d0,(a1)
                move.b  1(a2),d1
                bne.s   loc_608
                moveq   #$FFFFFFFF,d0

loc_608:                                ; CODE XREF: ROM:00000604↑j
                clr.b   1(a2)
                movem.l (sp)+,d1/a0-a2
                rts
; ---------------------------------------------------------------------------
                movem.l d0/d7/a1/a4,-(sp)
                lea     dword_1DE0(pc),a1
                move.w  d0,d7
                andi.w  #$F,d7
                cmp.w   #$F,d7
                bne.s   loc_62C
                jsr     (trap_7_instruction_entry).l ; "Copyright (1993) Imagitec Design, Inc "

loc_62C:                                ; CODE XREF: ROM:00000624↑j
                not.l   d0
                move.l  d0,(trap_7_instruction_entry).l ; "Copyright (1993) Imagitec Design, Inc "
                movem.l (sp)+,d0/d7/a1/a4
                rts
; ---------------------------------------------------------------------------
                movem.l d7/a1/a4,-(sp)
                lea     dword_1DE0(pc),a1
                moveq   #0,d7
                not.l   d7
                move.l  d7,(trap_7_instruction_entry).l ; "Copyright (1993) Imagitec Design, Inc "
                tst.b   $27(a1)
                beq.s   loc_658
                jsr     (trap_7_instruction_entry).l ; "Copyright (1993) Imagitec Design, Inc "

loc_658:                                ; CODE XREF: ROM:00000650↑j
                movem.l (sp)+,d7/a1/a4
                rts
; ---------------------------------------------------------------------------
                dc.w $436F
                dc.l $70797269, $67687420, $28313939, $33292049, $6D616769
                dc.l $74656320, $44657369, $676E2C20, $496E6320

; =============== S U B R O U T I N E =======================================


sub_684:                                ; CODE XREF: ROM:0000011A↑p
                bsr.s   sub_68C
                bsr.w   sub_758
                rts
; End of function sub_684


; =============== S U B R O U T I N E =======================================


sub_68C:                                ; CODE XREF: sub_684↑p
                lea     byte_FFE(pc),a5
                move.l  a0,dword_100E-byte_FFE(a5)
                move.w  #$1D8,d0
                move.w  #$258,d1
                cmpi.l  #$4D2E4B2E,$438(a0)
                bne.s   loc_6AE
                move.w  #$3B8,d0
                move.w  #$43C,d1

loc_6AE:                                ; CODE XREF: sub_68C+18↑j
                lea     (a0,d0.w),a1
                lea     (a0,d1.w),a2
                move.l  a1,$14(a5)
                move.l  a2,$18(a5)
                moveq   #0,d0
                move.b  (a1),d0
                lsl.l   #8,d0
                lsl.l   #2,d0
                add.l   a2,d0
                move.l  d0,8(a5)
                clr.l   $C(a5)
                adda.w  #$14,a0
                move.b  -2(a1),0(a5)
                moveq   #$7F,d0
                moveq   #0,d1

loc_6DE:                                ; CODE XREF: sub_68C:loc_6E6↓j
                cmp.b   (a1)+,d1
                bge.s   loc_6E6
                move.b  -1(a1),d1

loc_6E6:                                ; CODE XREF: sub_68C+54↑j
                dbf     d0,loc_6DE
                move.b  #6,2(a5)
                move.b  #0,1(a5)
                move.b  #0,3(a5)
                moveq   #7,d0
                lea     word_FDE(pc),a6

loc_702:                                ; CODE XREF: sub_68C+78↓j
                clr.l   (a6)+
                dbf     d0,loc_702
                moveq   #$33,d0 ; '3'
                lea     $210(a5),a6

loc_70E:                                ; CODE XREF: sub_68C+84↓j
                clr.l   (a6)+
                dbf     d0,loc_70E
                lea     $244(a5),a6
                move.w  #8,$20(a6)
                lea     $278(a5),a6
                move.w  #$10,$20(a6)
                lea     $2AC(a5),a6
                move.w  #$18,$20(a6)
                lea     $1C(a5),a5
                lea     dword_814(pc),a6
                moveq   #$1E,d0

loc_73C:                                ; CODE XREF: sub_68C+BE↓j
                move.l  a6,(a5)+
                move.w  #1,(a5)+
                move.l  a6,(a5)+
                move.w  #2,(a5)+
                clr.l   (a5)+
                dbf     d0,loc_73C
                lea     dword_7E0(pc),a5
                movem.l d0-d7/a0-a4,(a5)
                rts
; End of function sub_68C


; =============== S U B R O U T I N E =======================================


sub_758:                                ; CODE XREF: sub_684+2↑p
                lea     dword_7E0(pc),a5
                movem.l (a5),d0-d7/a0-a4
                lea     byte_FFE(pc),a5
                addq.w  #1,d1
                lsl.l   #8,d1
                lsl.l   #2,d1
                lea     (a2,d1.l),a2
                lea     $1C(a5),a3
                move.l  $14(a5),d0
                sub.l   a0,d0
                subq.l  #2,d0
                divu.w  #$1E,d0
                subq.w  #1,d0

loc_780:                                ; CODE XREF: sub_758+82↓j
                moveq   #0,d1
                moveq   #0,d2
                moveq   #0,d3
                move.w  $16(a0),d1
                move.w  $1C(a0),d3
                move.w  $1A(a0),d2
                bne.s   loc_79C
                add.l   d1,d1
                add.l   d3,d3
                move.l  d1,d4
                bra.s   loc_7B8
; ---------------------------------------------------------------------------

loc_79C:                                ; CODE XREF: sub_758+3A↑j
                move.l  d2,d4
                add.l   d3,d4
                cmp.l   d1,d4
                bgt.s   loc_7A6
                add.l   d2,d2

loc_7A6:                                ; CODE XREF: sub_758+4A↑j
                add.l   d1,d1
                add.l   d3,d3
                move.l  d2,d4
                add.l   d3,d4
                cmp.l   d1,d4
                ble.s   loc_7B8
                move.l  d1,d3
                sub.l   d2,d3
                move.l  d1,d4

loc_7B8:                                ; CODE XREF: sub_758+42↑j
                                        ; sub_758+58↑j
                move.l  a2,(a3)+
                lsr.l   #1,d3
                lsr.l   #1,d4
                move.w  d4,(a3)+
                move.l  a2,(a3)
                add.l   d2,(a3)+
                move.w  d3,(a3)+
                moveq   #0,d2
                move.b  $18(a0),d2
                move.w  d2,(a3)+
                move.b  $19(a0),d2
                move.w  d2,(a3)+
                adda.l  d1,a2
                lea     $1E(a0),a0
                dbf     d0,loc_780
                rts
; End of function sub_758

; ---------------------------------------------------------------------------
dword_7E0:      dcb.l $D,0              ; DATA XREF: sub_68C+C2↑o
                                        ; sub_758↑o
dword_814:      dcb.l 4,0               ; DATA XREF: sub_68C+AA↑o

; =============== S U B R O U T I N E =======================================


sub_824:                                ; CODE XREF: ROM:000001A2↑p
                movem.l d0-d7/a0-a6,-(sp)
                lea     byte_FFE(pc),a5
                lea     byte_FFF-byte_FFE(a5),a0
                lea     loc_B16(pc),a1
                move.b  (a0)+,d0
                addq.b  #1,d0
                cmp.b   (a0),d0
                blt.s   loc_862
                clr.b   -(a0)
                bsr.w   sub_8EE
                lea     $790(a5),a0
                tst.b   (a0)+
                beq.s   loc_850
                move.b  -(a0),1(a0)
                clr.b   (a0)+

loc_850:                                ; CODE XREF: sub_824+24↑j
                tst.b   (a0)
                beq.s   loc_860
                subq.b  #1,(a0)
                beq.s   loc_860
                subi.l  #$10,$C(a5)

loc_860:                                ; CODE XREF: sub_824+2E↑j
                                        ; sub_824+32↑j
                bra.s   loc_864
; ---------------------------------------------------------------------------

loc_862:                                ; CODE XREF: sub_824+16↑j
                move.b  d0,-(a0)

loc_864:                                ; CODE XREF: sub_824:loc_860↑j
                lea     $210(a5),a0
                bsr.w   sub_A9C
                lea     $244(a5),a0
                bsr.w   sub_A9C
                lea     $278(a5),a0
                bsr.w   sub_A9C
                lea     $2AC(a5),a0
                bsr.w   sub_A9C
                tst.b   5(a5)
                beq.s   loc_89E
                sf      5(a5)
                moveq   #0,d0
                move.b  6(a5),d0
                lsl.w   #4,d0
                move.l  d0,$C(a5)
                clr.w   6(a5)

loc_89E:                                ; CODE XREF: sub_824+64↑j
                cmpi.l  #$400,$C(a5)
                blt.s   loc_8E2

loc_8A8:                                ; CODE XREF: sub_824+C2↓j
                moveq   #0,d0
                move.b  6(a5),d0
                lsl.w   #4,d0
                move.l  d0,$C(a5)
                move.b  3(a5),d0
                addq.b  #1,d0
                cmp.b   0(a5),d0
                blt.s   loc_8C2
                clr.b   d0

loc_8C2:                                ; CODE XREF: sub_824+9A↑j
                move.b  d0,3(a5)
                movea.l $14(a5),a0
                move.b  (a0,d0.w),d0
                lsl.l   #8,d0
                lsl.l   #2,d0
                add.l   $18(a5),d0
                move.l  d0,8(a5)
                sf      6(a5)
                sf      7(a5)

loc_8E2:                                ; CODE XREF: sub_824+82↑j
                tst.b   7(a5)
                bne.s   loc_8A8
                movem.l (sp)+,d0-d7/a0-a6
                rts
; End of function sub_824


; =============== S U B R O U T I N E =======================================


sub_8EE:                                ; CODE XREF: sub_824+1A↑p
                tst.b   $791(a5)
                beq.s   loc_8FE
                addi.l  #$10,$C(a5)
                rts
; ---------------------------------------------------------------------------

loc_8FE:                                ; CODE XREF: sub_8EE+4↑j
                movea.l 8(a5),a0
                adda.l  $C(a5),a0
                addi.l  #$10,$C(a5)
                lea     $210(a5),a1
                lea     word_FDE(pc),a2
                bsr.s   sub_93C
                lea     $244(a5),a1
                lea     word_FE6(pc),a2
                bsr.s   sub_93C
                lea     $278(a5),a1
                lea     word_FEE(pc),a2
                bsr.s   sub_93C
                lea     $2AC(a5),a1
                lea     word_FF6(pc),a2
                bsr.s   sub_93C
                lea     word_B06(pc),a1
                rts
; End of function sub_8EE


; =============== S U B R O U T I N E =======================================


sub_93C:                                ; CODE XREF: sub_8EE+28↑p
                                        ; sub_8EE+32↑p ...
                move.l  (a0)+,d0
                move.l  d0,0(a1)
                move.w  d0,d1
                swap    d0
                move.w  d0,d2
                andi.w  #$F000,d1
                andi.w  #$F000,d2
                lsr.w   #4,d1
                or.w    d2,d1
                beq.s   loc_988
                subq.w  #1,d1
                lsr.w   #4,d1
                andi.w  #$1F0,d1
                st      $33(a1)
                lsr.w   #4,d1
                move.b  d1,$32(a1)
                lsl.w   #4,d1
                lea     6(a1),a3
                lea     $1C(a5),a4
                adda.w  d1,a4
                move.l  (a4)+,(a3)+
                move.l  (a4)+,(a3)+
                move.l  (a4)+,(a3)+
                move.w  (a4)+,(a3)+
                move.w  (a4),2(a3)
                movea.l $C(a1),a3
                move.l  a3,$2A(a1)

loc_988:                                ; CODE XREF: sub_93C+18↑j
                andi.w  #$FFF,d0
                beq.w   locret_A94
                move.b  2(a1),d1
                andi.w  #$F,d1
                cmp.b   #3,d1
                beq.w   loc_A4A
                cmp.b   #5,d1
                beq.w   loc_A4A
                cmp.b   #9,d1
                bne.s   loc_9D8
                moveq   #0,d1
                move.b  3(a1),d1
                beq.s   loc_9BA
                move.b  d1,$23(a1)

loc_9BA:                                ; CODE XREF: sub_93C+78↑j
                move.b  $23(a1),d1
                lsl.w   #7,d1
                cmp.w   $A(a1),d1
                bge.s   loc_9D2
                sub.w   d1,$A(a1)
                add.w   d1,d1
                add.l   d1,6(a1)
                bra.s   loc_9D8
; ---------------------------------------------------------------------------

loc_9D2:                                ; CODE XREF: sub_93C+88↑j
                move.w  #1,$A(a1)

loc_9D8:                                ; CODE XREF: sub_93C+70↑j
                                        ; sub_93C+94↑j
                move.l  d0,d1
                swap    d1
                andi.w  #$FF0,d1
                cmp.w   #$E50,d1
                bne.s   loc_9F4
                moveq   #0,d2
                move.b  3(a1),d2
                andi.w  #$F,d2
                move.w  d2,$12(a1)

loc_9F4:                                ; CODE XREF: sub_93C+A8↑j
                move.w  $12(a1),d2
                beq.s   loc_A14
                lea     $310(a5),a3
                moveq   #$24,d2 ; '$'

loc_A00:                                ; CODE XREF: sub_93C+C8↓j
                cmp.w   (a3)+,d0
                bcc.s   loc_A08
                dbf     d2,loc_A00

loc_A08:                                ; CODE XREF: sub_93C+C6↑j
                move.w  $12(a1),d2
                mulu.w  #$48,d2 ; 'H'
                move.w  -2(a3,d2.w),d0

loc_A14:                                ; CODE XREF: sub_93C+BC↑j
                move.w  d0,$14(a1)
                cmp.w   #$ED0,d1
                beq.w   locret_A94
                btst    #2,$22(a1)
                bne.s   loc_A2C
                clr.b   $25(a1)

loc_A2C:                                ; CODE XREF: sub_93C+EA↑j
                btst    #6,$22(a1)
                bne.s   loc_A38
                clr.b   $25(a1)

loc_A38:                                ; CODE XREF: sub_93C+F6↑j
                move.l  6(a1),0(a2)
                move.w  $A(a1),4(a2)
                asl     4(a2)
                rts
; ---------------------------------------------------------------------------

loc_A4A:                                ; CODE XREF: sub_93C+60↑j
                                        ; sub_93C+68↑j
                move.w  $12(a1),d1
                mulu.w  #$48,d1 ; 'H'
                lea     $310(a5),a3
                adda.l  d1,a3
                moveq   #0,d1

loc_A5A:                                ; CODE XREF: sub_93C+12A↓j
                cmp.w   (a3,d1.w),d0
                bcc.s   loc_A6A
                addq.w  #2,d1
                cmp.w   #$48,d1 ; 'H'
                bcs.s   loc_A5A
                moveq   #$46,d1 ; 'F'

loc_A6A:                                ; CODE XREF: sub_93C+122↑j
                move.w  $12(a1),d0
                andi.b  #8,d0
                beq.s   loc_A7A
                tst.w   d1
                beq.s   loc_A7A
                subq.w  #2,d1

loc_A7A:                                ; CODE XREF: sub_93C+136↑j
                                        ; sub_93C+13A↑j
                move.w  (a3,d1.w),d0
                move.w  d0,$1C(a1)
                clr.b   $1E(a1)
                cmp.w   $14(a1),d0
                beq.s   loc_A96
                bgt.s   locret_A94
                move.b  #1,$1E(a1)

locret_A94:                             ; CODE XREF: sub_93C+50↑j
                                        ; sub_93C+E0↑j ...
                rts
; ---------------------------------------------------------------------------

loc_A96:                                ; CODE XREF: sub_93C+14E↑j
                clr.w   $1C(a1)
                rts
; End of function sub_93C


; =============== S U B R O U T I N E =======================================


sub_A9C:                                ; CODE XREF: sub_824+44↑p
                                        ; sub_824+4C↑p ...
                move.l  a1,-(sp)
                movem.l a0-a1,-(sp)
                bsr.w   sub_F84
                movem.l (sp)+,a0-a1
                lea     $14(a0),a2
                move.l  (a2)+,(a2)
                moveq   #0,d0
                move.w  2(a0),d0
                andi.w  #$FFF,d0
                beq.s   loc_AD6
                move.l  d0,d1
                andi.w  #$FF,d1
                lsr.w   #8,d0
                tst.b   (a1,d0.w)
                beq.s   loc_AD6
                add.w   d0,d0
                lea     word_AE6(pc),a1
                adda.w  (a1,d0.w),a1
                jsr     (a1)

loc_AD6:                                ; CODE XREF: sub_A9C+1E↑j
                                        ; sub_A9C+2C↑j
                move.w  $20E(a5),d0
                mulu.w  $1A(a0),d0
                move.w  d0,$1A(a0)
                movea.l (sp)+,a1
                rts
; End of function sub_A9C

; ---------------------------------------------------------------------------
word_AE6:       dc.w $40                ; DATA XREF: sub_A9C+30↑o
                dc.l $9800B4, $D0014E, $1E401F4, $20402A8, $2AA02D2, $3000310
                dc.l $3220344
                dc.b 4, $E8
word_B06:       dc.w 0                  ; DATA XREF: sub_8EE+48↑o
                dc.l 0
                dc.l 1, $10101
; ---------------------------------------------------------------------------
                btst    d0,d1

loc_B16:                                ; DATA XREF: sub_824+C↑o
                btst    d0,d1
                btst    d0,d1
                btst    d0,d1
                btst    d0,d1
                ; Not sure what these instructions are.
                ; Some variant of ori.b #1,d0 ?
                dc.l $00000100
                dc.l $00000100
                moveq   #0,d0
                move.b  1(a5),d0
                divs.w  #3,d0
                swap    d0
                cmp.w   #0,d0
                beq.s   loc_B4C
                cmp.w   #2,d0
                beq.s   loc_B44
                move.l  d1,d0
                lsr.b   #4,d0
                bra.s   loc_B52
; ---------------------------------------------------------------------------

loc_B44:                                ; CODE XREF: ROM:00000B3C↑j
                move.l  d1,d0
                andi.b  #$F,d0
                bra.s   loc_B52
; ---------------------------------------------------------------------------

loc_B4C:                                ; CODE XREF: ROM:00000B36↑j
                move.w  $14(a0),d2
                bra.s   loc_B78
; ---------------------------------------------------------------------------

loc_B52:                                ; CODE XREF: ROM:00000B42↑j
                                        ; ROM:00000B4A↑j
                add.w   d0,d0
                move.w  $12(a0),d1
                mulu.w  #$48,d1 ; 'H'
                lea     $310(a5),a1
                adda.l  d1,a1
                move.w  $14(a0),d1
                moveq   #$24,d7 ; '$'

loc_B68:                                ; CODE XREF: ROM:00000B72↓j
                move.w  (a1,d0.w),d2
                cmp.w   (a1),d1
                bcc.s   loc_B78
                addq.l  #2,a1
                dbf     d7,loc_B68
                rts
; ---------------------------------------------------------------------------

loc_B78:                                ; CODE XREF: ROM:00000B50↑j
                                        ; ROM:00000B6E↑j
                move.w  d2,$18(a0)
                rts
; ---------------------------------------------------------------------------
                sub.w   d1,$14(a0)
                cmpi.w  #$71,$14(a0) ; 'q'
                bge.s   loc_B90
                move.w  #$71,$14(a0) ; 'q'

loc_B90:                                ; CODE XREF: ROM:00000B88↑j
                move.w  $14(a0),d0
                move.w  d0,$18(a0)
                rts
; ---------------------------------------------------------------------------
                add.w   d1,$14(a0)
                cmpi.w  #$358,$14(a0)
                ble.s   loc_BAC
                move.w  #$358,$14(a0)

loc_BAC:                                ; CODE XREF: ROM:00000BA4↑j
                move.w  $14(a0),d0
                move.w  d0,$18(a0)
                rts
; ---------------------------------------------------------------------------
                tst.w   d1
                beq.s   sub_BC2
                move.b  d1,$1F(a0)
                clr.b   3(a0)

; =============== S U B R O U T I N E =======================================


sub_BC2:                                ; CODE XREF: ROM:00000BB8↑j
                                        ; ROM:00000CCA↓p
                move.w  $1C(a0),d2
                bne.s   loc_BCA
                rts
; ---------------------------------------------------------------------------

loc_BCA:                                ; CODE XREF: sub_BC2+4↑j
                moveq   #0,d0
                move.b  $1F(a0),d0
                tst.b   $1E(a0)
                beq.s   loc_BEA
                sub.w   d0,$14(a0)
                cmp.w   $14(a0),d2
                blt.s   loc_BFC
                move.w  d2,$14(a0)
                clr.w   $1C(a0)
                bra.s   loc_BFC
; ---------------------------------------------------------------------------

loc_BEA:                                ; CODE XREF: sub_BC2+12↑j
                add.w   d0,$14(a0)
                cmp.w   $14(a0),d2
                bgt.s   loc_BFC
                move.w  d2,$14(a0)
                clr.w   $1C(a0)

loc_BFC:                                ; CODE XREF: sub_BC2+1C↑j
                                        ; sub_BC2+26↑j ...
                move.w  $14(a0),d0
                move.b  $28(a0),d1
                andi.b  #$F,d1
                beq.s   loc_C2E
                move.w  $12(a0),d1
                mulu.w  #$48,d1 ; 'H'
                lea     $310(a5),a1
                adda.l  d1,a1
                moveq   #0,d1

loc_C1A:                                ; CODE XREF: sub_BC2+64↓j
                cmp.w   (a1,d1.w),d0
                bcc.s   loc_C2A
                addq.w  #2,d1
                cmp.w   #$48,d1 ; 'H'
                bcs.s   loc_C1A
                moveq   #$46,d1 ; 'F'

loc_C2A:                                ; CODE XREF: sub_BC2+5C↑j
                move.w  (a1,d1.w),d0

loc_C2E:                                ; CODE XREF: sub_BC2+46↑j
                move.w  d0,$18(a0)
                rts
; End of function sub_BC2

; ---------------------------------------------------------------------------
                tst.w   d1
                beq.s   sub_C5C
                move.b  $24(a0),d2
                andi.b  #$F,d1
                beq.s   loc_C48
                andi.b  #$F0,d2
                or.b    d1,d2

loc_C48:                                ; CODE XREF: ROM:00000C40↑j
                move.b  3(a0),d1
                andi.b  #$F0,d1
                beq.s   loc_C58
                andi.b  #$F,d2
                or.w    d1,d2

loc_C58:                                ; CODE XREF: ROM:00000C50↑j
                move.b  d2,$24(a0)

; =============== S U B R O U T I N E =======================================


sub_C5C:                                ; CODE XREF: ROM:00000C36↑j
                                        ; ROM:00000CDA↓p
                lea     $2F0(a5),a1
                move.b  $25(a0),d0
                lsr.w   #2,d0
                andi.w  #$1F,d0
                moveq   #0,d1
                move.b  $22(a0),d1
                andi.b  #3,d1
                beq.s   loc_C96
                lsl.b   #3,d0
                cmp.b   #1,d1
                beq.s   loc_C84
                move.b  #$FF,d1
                bra.s   loc_C9A
; ---------------------------------------------------------------------------

loc_C84:                                ; CODE XREF: sub_C5C+20↑j
                tst.b   $25(a0)
                bpl.s   loc_C92
                move.b  #$FF,d1
                sub.b   d0,d1
                bra.s   loc_C9A
; ---------------------------------------------------------------------------

loc_C92:                                ; CODE XREF: sub_C5C+2C↑j
                move.b  d0,d1
                bra.s   loc_C9A
; ---------------------------------------------------------------------------

loc_C96:                                ; CODE XREF: sub_C5C+18↑j
                move.b  (a1,d0.w),d1

loc_C9A:                                ; CODE XREF: sub_C5C+26↑j
                                        ; sub_C5C+34↑j ...
                move.b  $24(a0),d0
                andi.w  #$F,d0
                mulu.w  d0,d1
                lsr.w   #7,d1
                move.w  $14(a0),d0
                tst.b   $25(a0)
                bmi.s   loc_CB4
                add.w   d1,d0
                bra.s   loc_CB6
; ---------------------------------------------------------------------------

loc_CB4:                                ; CODE XREF: sub_C5C+52↑j
                sub.w   d1,d0

loc_CB6:                                ; CODE XREF: sub_C5C+56↑j
                move.w  d0,$18(a0)
                move.b  $24(a0),d0
                lsr.w   #2,d0
                andi.w  #$3C,d0 ; '<'
                add.b   d0,$25(a0)
                rts
; End of function sub_C5C

; ---------------------------------------------------------------------------
                bsr.w   sub_BC2
                moveq   #0,d1
                move.b  3(a0),d1
                bsr.w   sub_DB8
                rts
; ---------------------------------------------------------------------------
                bsr.w   sub_C5C
                moveq   #0,d1
                move.b  3(a0),d1
                bsr.w   sub_DB8
                rts
; ---------------------------------------------------------------------------
                tst.w   d1
                beq.s   loc_D12
                move.b  $24(a0),d2
                andi.b  #$F,d1
                beq.s   loc_CFE
                andi.b  #$F0,d2
                or.b    d1,d2

loc_CFE:                                ; CODE XREF: ROM:00000CF6↑j
                move.b  3(a0),d1
                andi.b  #$F0,d1
                beq.s   loc_D0E
                andi.b  #$F,d2
                or.w    d1,d2

loc_D0E:                                ; CODE XREF: ROM:00000D06↑j
                move.b  d2,$24(a0)

loc_D12:                                ; CODE XREF: ROM:00000CEC↑j
                lea     $2F0(a5),a1
                move.b  $25(a0),d0
                lsr.w   #2,d0
                andi.w  #$1F,d0
                moveq   #0,d1
                move.b  $22(a0),d1
                lsr.b   #4,d1
                andi.b  #3,d1
                beq.s   loc_D4E
                lsl.b   #3,d0
                cmp.b   #1,d1
                beq.s   loc_D3C
                move.b  #$FF,d1
                bra.s   loc_D52
; ---------------------------------------------------------------------------

loc_D3C:                                ; CODE XREF: ROM:00000D34↑j
                tst.b   $25(a0)
                bpl.s   loc_D4A
                move.b  #$FF,d1
                sub.b   d0,d1
                bra.s   loc_D52
; ---------------------------------------------------------------------------

loc_D4A:                                ; CODE XREF: ROM:00000D40↑j
                move.b  d0,d1
                bra.s   loc_D52
; ---------------------------------------------------------------------------

loc_D4E:                                ; CODE XREF: ROM:00000D2C↑j
                move.b  (a1,d0.w),d1

loc_D52:                                ; CODE XREF: ROM:00000D3A↑j
                                        ; ROM:00000D48↑j ...
                move.b  $24(a0),d0
                andi.w  #$F,d0
                mulu.w  d0,d1
                lsr.w   #6,d1
                move.w  $16(a0),d0
                tst.b   $25(a0)
                bmi.s   loc_D6C
                add.w   d1,d0
                bra.s   loc_D6E
; ---------------------------------------------------------------------------

loc_D6C:                                ; CODE XREF: ROM:00000D66↑j
                sub.w   d1,d0

loc_D6E:                                ; CODE XREF: ROM:00000D6A↑j
                bpl.s   loc_D72
                moveq   #0,d0

loc_D72:                                ; CODE XREF: ROM:loc_D6E↑j
                cmp.w   #$40,d0 ; '@'
                ble.s   loc_D7A
                moveq   #$40,d0 ; '@'

loc_D7A:                                ; CODE XREF: ROM:00000D76↑j
                move.w  d0,$1A(a0)
                move.b  $24(a0),d0
                lsr.w   #2,d0
                andi.w  #$3C,d0 ; '<'
                add.b   d0,$25(a0)
                rts
; ---------------------------------------------------------------------------
                rts
; ---------------------------------------------------------------------------
                tst.w   d1
                beq.s   loc_D98
                move.b  d1,$23(a0)

loc_D98:                                ; CODE XREF: ROM:00000D92↑j
                move.b  $23(a0),d1
                lsl.w   #7,d1
                cmp.w   $A(a0),d1
                bge.s   loc_DB0
                sub.w   d0,$A(a0)
                add.w   d0,d0
                add.l   d0,6(a0)
                rts
; ---------------------------------------------------------------------------

loc_DB0:                                ; CODE XREF: ROM:00000DA2↑j
                move.w  #1,$A(a0)
                rts

; =============== S U B R O U T I N E =======================================


sub_DB8:                                ; CODE XREF: ROM:00000CD4↑p
                                        ; ROM:00000CE4↑p
                move.w  $16(a0),d3
                move.w  d1,d2
                lsr.w   #4,d1
                andi.w  #$F,d1
                beq.s   loc_DD2
                add.w   d1,d3
                cmp.w   #$40,d3 ; '@'
                ble.s   loc_DDC
                moveq   #$40,d3 ; '@'
                bra.s   loc_DDC
; ---------------------------------------------------------------------------

loc_DD2:                                ; CODE XREF: sub_DB8+C↑j
                andi.w  #$F,d2
                sub.w   d2,d3
                bpl.s   loc_DDC
                moveq   #0,d3

loc_DDC:                                ; CODE XREF: sub_DB8+14↑j
                                        ; sub_DB8+18↑j ...
                move.w  d3,$16(a0)
                move.w  d3,$1A(a0)
                rts
; End of function sub_DB8

; ---------------------------------------------------------------------------
                subq.w  #1,d1
                move.b  d1,3(a5)
                clr.b   6(a5)
                st      7(a5)
                rts
; ---------------------------------------------------------------------------
                cmp.w   #$40,d1 ; '@'
                ble.s   loc_DFE
                moveq   #$40,d1 ; '@'

loc_DFE:                                ; CODE XREF: ROM:00000DFA↑j
                move.w  d1,$16(a0)
                move.w  d1,$1A(a0)
                rts
; ---------------------------------------------------------------------------
                clr.b   6(a5)
                st      7(a5)
                move.l  d1,d2
                lsr.b   #4,d1
                mulu.w  #$A,d1
                andi.b  #$F,d2
                add.b   d2,d1
                cmp.b   #$3F,d1 ; '?'
                bhi.s   locret_E28
                move.b  d1,6(a5)

locret_E28:                             ; CODE XREF: ROM:00000E22↑j
                rts
; ---------------------------------------------------------------------------
                move.w  d1,d2
                andi.w  #$F,d1
                lsr.w   #4,d2
                add.w   d2,d2
                lea     dword_E40(pc),a1
                adda.w  (a1,d2.w),a1
                jsr     (a1)
                rts
; ---------------------------------------------------------------------------
dword_E40:      dc.l $200022, $2E003A, $460052, $580090, $9E00A0, $DE00EC
                                        ; DATA XREF: ROM:00000E34↑o
                dc.l $F80108, $11A012E, $4E754A2D, $16604, $6100FD14, $4E754A2D
                dc.l $16604, $6100FD24, $4E750228, $F00028, $83280028
                dc.l $4E750228, $F00022, $83280022, $4E751141, $124E75
                dc.l $4A2D0001, $66304A41, $67204A28, $266714, $53280026
                dc.l $67201028, $271B40, $650ED, $54E75, $11410026, $60EC222D
                dc.l $CE849, $53011141, $274E75, $E9090228, $F0022, $83280022
                dc.l $4E754E75, $4A416738, $7400142D, $16610, $34280000
                dc.l $2420FFF, $66267400, $142D0001, $84C14842, $4A426618
                dc.l $32280020, $4DFA00D4, $2DA80006, $10003DA8, $A1004
                dc.l $E1F61004, $4E754A2D, $16606, $E9096100, $FE904E75
                dc.l $4A2D0001, $66046100, $FE844E75, $B22D0001, $66084268
                dc.l $164268, $1A4E75, $B22D0001, $660A4A68, $6704, $6100FFAE
                dc.l $4E754A2D, $1660C, $4A2D0791, $66065201, $1B410790
                dc.l $4E754A2D, $16658, $E9090228, $F0028, $83280028, $4A016748

; =============== S U B R O U T I N E =======================================


sub_F84:                                ; CODE XREF: sub_A9C+6↑p
                moveq   #0,d1
                move.b  $28(a0),d1
                lsr.b   #4,d1
                beq.s   locret_FCC
                lea     $2E0(a5),a1
                move.b  (a1,d1.w),d1
                add.b   d1,$29(a0)
                btst    #7,$29(a0)
                beq.s   locret_FCC
                clr.b   $29(a0)
                move.l  $C(a0),d0
                moveq   #0,d1
                move.w  $10(a0),d1
                add.l   d1,d0
                add.l   d1,d0
                movea.l $2A(a0),a1
                addq.l  #1,a1
                cmpa.l  d0,a1
                bcs.s   loc_FC2
                movea.l $C(a0),a1

loc_FC2:                                ; CODE XREF: sub_F84+38↑j
                move.l  a1,$2A(a0)
                moveq   #$FFFFFFFF,d0
                sub.b   (a0),d0
                move.b  d0,(a0)

locret_FCC:                             ; CODE XREF: sub_F84+8↑j
                                        ; sub_F84+1C↑j
                rts
; End of function sub_F84

; ---------------------------------------------------------------------------
                andi.w  #$1F,d1
                beq.s   locret_FDC
                move.b  d1,2(a5)
                clr.b   1(a5)

locret_FDC:                             ; CODE XREF: ROM:00000FD2↑j
                rts
; ---------------------------------------------------------------------------
word_FDE:       dc.w 0                  ; DATA XREF: ROM:000001B4↑o
                                        ; sub_68C+72↑o ...
                dc.l 0
                dcb.b 2,0
word_FE6:       dc.w 0                  ; DATA XREF: sub_8EE+2E↑o
                dc.l 0
                dcb.b 2,0
word_FEE:       dc.w 0                  ; DATA XREF: sub_8EE+38↑o
                dc.l 0
                dcb.b 2,0
word_FF6:       dc.w 0                  ; DATA XREF: sub_8EE+42↑o
                dc.l 0
                dcb.b 2,0
byte_FFE:       dc.b 0                  ; DATA XREF: ROM:000001A6↑o
                                        ; ROM:00000476↑o ...
byte_FFF:       dc.b 0                  ; DATA XREF: sub_824+8↑o
                dcb.l 3,0
                dcb.b 2,0
dword_100E:     dc.l 0                  ; DATA XREF: sub_68C+4↑w
.long
                dcb.l $7E,0
word_120C:      dc.w $40                ; DATA XREF: ROM:0000047A↑w
                                        ; ROM:000004CC↑w ...
word_120E:      dc.w 0                  ; DATA XREF: ROM:000005F0↑o
                dc.l 1
                dcb.l $C,0
                dc.l 2
                dcb.l 6,0
                dc.l 8
                dcb.l 5,0
                dc.l 4
                dcb.l 6,0
                dc.l $10
                dcb.l 5,0
                dc.l 8
                dcb.l 6,0
                dc.l $18
                dcb.l 4,0
                dc.l 5, $607080A, $B0D1013, $161A202B, $40800018, $314A6178
                dc.l $8DA1B4C5, $D4E0EBF4, $FAFDFFFD, $FAF4EBE0, $D4C5B4A1
                dc.l $8D78614A, $31180358, $32802FA, $2D002A6, $280025C
                dc.l $23A021A, $1FC01E0, $1C501AC, $194017D, $1680153
                dc.l $140012E, $11D010D, $FE00F0, $E200D6, $CA00BE, $B400AA
                dc.l $A00097, $8F0087, $7F0078, $710352, $32202F5, $2CB02A2
                dc.l $27D0259, $2370217, $1F901DD, $1C201A9, $191017B
                dc.l $1650151, $13E012C, $11C010C, $FD00EF, $E100D5, $C900BD
                dc.l $B300A9, $9F0096, $8E0086, $7E0077, $71034C, $31C02F0
                dc.l $2C5029E, $2780255, $2330214, $1F601DA, $1BF01A6
                dc.l $18E0178, $163014F, $13C012A, $11A010A, $FB00ED, $E000D3
                dc.l $C700BC, $B100A7, $9E0095, $8D0085, $7D0076, $700346
                dc.l $31702EA, $2C00299, $2740250, $22F0210, $1F201D6
                dc.l $1BC01A3, $18B0175, $160014C, $13A0128, $1180108
                dc.l $F900EB, $DE00D1, $C600BB, $B000A6, $9D0094, $8C0084
                dc.l $7D0076, $6F0340, $31102E5, $2BB0294, $26F024C, $22B020C
                dc.l $1EF01D3, $1B901A0, $1880172, $15E014A, $1380126
                dc.l $1160106, $F700E9, $DC00D0, $C400B9, $AF00A5, $9C0093
                dc.l $8B0083, $7C0075, $6E033A, $30B02E0, $2B6028F, $26B0248
                dc.l $2270208, $1EB01CF, $1B5019D, $1860170, $15B0148
                dc.l $1350124, $1140104, $F500E8, $DB00CE, $C300B8, $AE00A4
                dc.l $9B0092, $8A0082, $7B0074, $6D0334, $30602DA, $2B1028B
                dc.l $2660244, $2230204, $1E701CC, $1B2019A, $183016D
                dc.l $1590145, $1330122, $1120102, $F400E6, $D900CD, $C100B7
                dc.l $AC00A3, $9A0091, $890081, $7A0073, $6D032E, $30002D5
                dc.l $2AC0286, $262023F, $21F0201, $1E401C9, $1AF0197
                dc.l $180016B, $1560143, $1310120, $1100100, $F200E4, $D800CC
                dc.l $C000B5, $AB00A1, $980090, $880080, $790072, $6C038B
                dc.l $3580328, $2FA02D0, $2A60280, $25C023A, $21A01FC
                dc.l $1E001C5, $1AC0194, $17D0168, $1530140, $12E011D
                dc.l $10D00FE, $F000E2, $D600CA, $BE00B4, $AA00A0, $97008F
                dc.l $87007F, $780384, $3520322, $2F502CB, $2A3027C, $2590237
                dc.l $21701F9, $1DD01C2, $1A90191, $17B0165, $151013E
                dc.l $12C011C, $10C00FD, $EE00E1, $D400C8, $BD00B3, $A9009F
                dc.l $96008E, $86007E, $77037E, $34C031C, $2F002C5, $29E0278
                dc.l $2550233, $21401F6, $1DA01BF, $1A6018E, $1780163
                dc.l $14F013C, $12A011A, $10A00FB, $ED00DF, $D300C7, $BC00B1
                dc.l $A7009E, $95008D, $85007D, $760377, $3460317, $2EA02C0
                dc.l $2990274, $250022F, $21001F2, $1D601BC, $1A3018B
                dc.l $1750160, $14C013A, $1280118, $10800F9, $EB00DE, $D100C6
                dc.l $BB00B0, $A6009D, $94008C, $84007D, $760371, $3400311
                dc.l $2E502BB, $294026F, $24C022B, $20C01EE, $1D301B9
                dc.l $1A00188, $172015E, $14A0138, $1260116, $10600F7
                dc.l $E900DC, $D000C4, $B900AF, $A5009C, $93008B, $83007B
                dc.l $75036B, $33A030B, $2E002B6, $28F026B, $2480227, $20801EB
                dc.l $1CF01B5, $19D0186, $170015B, $1480135, $1240114
                dc.l $10400F5, $E800DB, $CE00C3, $B800AE, $A4009B, $92008A
                dc.l $82007B, $740364, $3340306, $2DA02B1, $28B0266, $2440223
                dc.l $20401E7, $1CC01B2, $19A0183, $16D0159, $1450133
                dc.l $1220112, $10200F4, $E600D9, $CD00C1, $B700AC, $A3009A
                dc.l $910089, $81007A, $73035E, $32E0300, $2D502AC, $2860262
                dc.l $23F021F, $20101E4, $1C901AF, $1970180, $16B0156
                dc.l $1430131, $1200110, $10000F2, $E400D8, $CB00C0, $B500AB
                dc.l $A10098, $900088, $800079, $720000
                dcb.b 2,0
word_1792:      dc.w 0                  ; DATA XREF: ROM:00000142↑o
                                        ; initpit2+14↑o ...
                dcb.l $192,0
dword_1DDC:     dc.l $FFFFFFFF          ; DATA XREF: ROM:000005E2↑o
dword_1DE0:     dcb.l 4,0               ; DATA XREF: ROM:0000011E↑o
                                        ; ROM:000001C0↑o ...
dword_1DF0:     dc.l 2                  ; DATA XREF: ROM:00000124↑w
                                        ; ROM:000004F8↑w ...
                dc.l $10000, 0
                dc.b 0, $C0
dword_1DFE:     dc.l $60                ; DATA XREF: ROM:000004E0↑r
.long
                dc.b 1, 0
byte_1E06:      dc.b 1                  ; DATA XREF: ROM:000002C6↑r
                                        ; ROM:00000596↑w ...
byte_1E07:      dc.b 0                  ; DATA XREF: ROM:00000538↑w
                                        ; ROM:00000554↑w
dword_1E08:     dcb.l 3,0               ; DATA XREF: ROM:000003A0↑o
GPUSTART:
                dc.l $9800B022, $F1D000
                dcb.l 2,$E400E400
                dc.l $A53D3C7D, $A7FE395D, $85E089F, $8C20D3C0, $BD3D981F
                dc.l $B01000F1, $93FF9809, $A10000F1, $981BB800, $F19807
                dc.l $B36000F1, $980A0020, $980B, $FF0000, $980D7FFF, $91B9
                dc.l $980CFFFC, $FFFF981C, $B35800F1, $A52E38AE, $BD2EE400
                dc.l $E400980D, $B35800F1, $8B6FA5BC, $A5ED9812, $B0B600F1
                dc.l $798D88F3, $D242341C, $D242E400, $B063B0D3, $B0440073
                dc.l $B0217A64, $9033D554, $37E1D461, $88F3D240, $BDECB0A5
                dc.l $B0E28C13, $C845C882, $8A68C8D3, $6513B082, $25680053
                dc.l $9100014F, $A5ED9812, $B0FE00F1, $798D88F4, $D242343C
                dc.l $D242E400, $B063B0D4, $B0440074, $B0217A84, $9034D554
                dc.l $37E1D461, $88F4D240, $BDECB0A5, $B0E28C14, $C845C882
                dc.l $8A88C8D4, $6514B082, $25680054, $9101014F, $A5ED9812
                dc.l $B14600F1, $798D88F5, $D242345C, $D242E400, $B063B0D5
                dc.l $B0440075, $B0217AA4, $9035D554, $37E1D461, $88F5D240
                dc.l $BDECB0A5, $B0E28C15, $C845C882, $8AA8C8D5, $6515B082
                dc.l $25680055, $9102014F, $A5ED9812, $B18E00F1, $798D88F6
                dc.l $D242347C, $D242E400, $B063B0D6, $B0440076, $B0217AC4
                dc.l $9036D554, $37E1D461, $88F6D240, $BDECB0A5, $B0E28C16
                dc.l $C845C882, $8AC8C8D6, $6516B082, $25680056, $9103014F
                dc.l $A5ED9812, $B1D600F1, $798D88F7, $D242349C, $D242E400
                dc.l $B063B0D7, $B0440077, $B0217AE4, $9037D554, $37E1D461
                dc.l $88F7D240, $BDECB0A5, $B0E28C17, $C845C882, $8AE8C8D7
                dc.l $6517B082, $25680057, $9104014F, $A5ED9812, $B21E00F1
                dc.l $798D88F8, $D24234BC, $D242E400, $B063B0D8, $B0440078
                dc.l $B0217B04, $9038D554, $37E1D461, $88F8D240, $BDECB0A5
                dc.l $B0E28C18, $C845C882, $8B08C8D8, $6518B082, $25680058
                dc.l $91059E70, $C339206, $9E719E90, $92270C34, $92089E91
                dc.l $9EB09229, $C35920A, $9EB19ED0, $922B0C36, $920C9ED1
                dc.l $9EF0922D, $9F119210, $9232A52D, $39CDBD2D, $E400E400
                dc.l $957B6306, $101B6307, $47664407, $C7957B, $6308103B
                dc.l $63094768, $44290109, $957B630A, $105B630B, $476A444B
                dc.l $14B957B, $630C107B, $630D476C, $446D018D, $6D074667
                dc.l $6D096DE7, $46896D0B, $6DE946AB, $6D0D6DEB, $46CD6310
                dc.l $6DED46F0, $63126DF0, $47126DF2, $9806B35C, $F1980A
                dc.l $3FFF0000, $A4C89806, $B30200F1, $7C08D0C1, $E4009806
                dc.l $60000000, $98081FFF, $48E6, $51285168, $51A6520A
                dc.l $524A4C1D, $48E85126, $516651A8, $520A524A, $4C1E9806
                dc.l $B32400F1, $E400D0C0, $E400980A, $3FFF0000, $48EA512A
                dc.l $516A51AA, $520A524A, $4C1D48EA, $512A516A, $51AA520A
                dc.l $524A4C1E, $9534A693, $3DD3BE93, $E400E400, $7C00D7C2
                dc.l $E40097B9, $97DA980E, $A14800F1, $6DF96DFA, $8419841A
                dc.l $BDD9088E, $9812B066, $F1BDDA, $D2408C00
                dcb.l 2,$FFFFFFFF
                dc.l 0
; end of 'ROM'


                END
